import Head from "next/head";
import Image from "next/image";
import Barranav from "../../../components/layout/header/barranav";

export default function Home() {
  return (
    <>
    <Head>
        <title>Lista</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="/favicon.ico" />
        <Barranav />
      </Head>
    
    <main>
    <h1>Listas</h1>
      <p>Las listas se utilizan para organizar la información en una página web.</p>
      <h2>Etiqueta ul</h2>
      <p>La etiqueta ul se utiliza para crear una lista no ordenada.</p>
      <p>Una lista no ordenada comienza con la etiqueta ul y cada elemento de la lista comienza con la etiqueta li.</p>
      <p>Los elementos de la lista se muestran con viñetas.</p>
      <h2>Etiqueta ol</h2>
      <p>La etiqueta ol se utiliza para crear una lista ordenada.</p>
      <p>Una lista ordenada comienza con la etiqueta ol y cada elemento de la lista comienza con la etiqueta li.</p>
      <p>Los elementos de la lista se muestran con números o letras.</p>
      <h2>Etiqueta li</h2>
      <p>La etiqueta li se utiliza para definir un elemento de lista.</p>
      <p>La etiqueta li se utiliza en listas no ordenadas (ul) y listas ordenadas (ol).</p>
    <button><a href="/HTML">Anterior</a></button>
    </main>
    </>
  );
}

