import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Barranav from "../../../components/layout/header/barranav";



export default function Comp() {
  return (
    <>
      <Head>
        <title>Estados</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
        <Barranav />
      </Head>
      
      <main>


      
      <h1>Estados</h1>
      <p>El estado es un objeto que contiene datos y determina cómo se ve un componente.</p>
      <h2>useState</h2>
      <p>El hook useState se utiliza para añadir estado a un componente de función.</p>
      <h2>useEffect</h2>
      <p>El hook useEffect se utiliza para realizar efectos secundarios en un componente de función.</p>
      <h2>useContext</h2>
      <p>El hook useContext se utiliza para acceder al contexto en un componente de función.</p>
      <h2>useReducer</h2>
      <p>El hook useReducer se utiliza para manejar el estado en un componente de función.</p>
      <h2>useMemo</h2>
      <p>El hook useMemo se utiliza para memoizar un valor calculado en un componente de función.</p>
      <h2>useCallback</h2>
      <p>El hook useCallback se utiliza para memoizar una función en un componente de función.</p>
      <h2>useRef</h2>
      <p>El hook useRef se utiliza para acceder al DOM o a un componente hijo de un componente de función.</p>
      <h2>useImperativeHandle</h2>
      <p>El hook useImperativeHandle se utiliza para personalizar el valor de retorno de useRef en un componente de función.</p>
      <h2>useLayoutEffect</h2>
      <p>El hook useLayoutEffect se utiliza para realizar efectos secundarios en un componente de función de forma sincrónica.</p>
      <h2>useDebugValue</h2>
      <p>El hook useDebugValue se utiliza para mostrar un valor en las herramientas de desarrollo de React.</p>
      <h2>Conclusión</h2>
      <p>El estado es un objeto que contiene datos y determina cómo se ve un componente.</p>
      <h2>Referencias</h2>
      
      <Link href={"https://es.react.dev/learn"}>
        Get Started
      </Link>

      <br/>
      <br/>



      <button><a href="/React">Anterior</a></button>

      </main>

    </>
  );
}

