import Head from "next/head";
import Image from "next/image";
import Barranav from "../../../components/layout/header/barranav";


export default function Home() {
  return (
    <>
    <Head>
        <title>Imágenes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="/favicon.ico" />
        <Barranav />
      </Head>
    
    <main>
    <h1>Etiqueta img</h1>
    <p>La etiqueta img se utiliza para insertar una imagen en una página web.</p>
    <h2>Atributo src</h2>
    <p>El atributo src especifica la URL de la imagen.</p>
    <h2>Atributo alt</h2>
    <p>El atributo alt proporciona un texto alternativo para una imagen, si no se puede mostrar.</p>
    <h2>Atributo width</h2>
    <p>El atributo width especifica el ancho de la imagen en píxeles.</p>
    <h2>Atributo height</h2>
    <p>El atributo height especifica la altura de la imagen en píxeles.</p>
    <h2>Ejemplo</h2>
    <p> &lt;img src="/imagen.jpg" alt="Imagen de ejemplo" width="500" height="600"/&gt; </p>
      
    
      <button><a href="/HTML">Anterior</a></button>

    </main>
    </>
  );
}

