import Head from "next/head";
import Image from "next/image";
import Barranav from "../../components/layout/header/barranav";
import Title from "../../components/pages/html/header/titulo";
import Lista from "../../components/pages/html/header/lista";

export default function Html() {
  return (
    <>
      <Head>
        <title>HTML</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
        
      </Head>
      <header>
      <Barranav />
      </header>
      <main>
        <Title />
        <Lista />
      </main>
      <footer>
      </footer>
      

    </>
  );
}

