import Head from "next/head";
import Image from "next/image";
import Barranav from "../../../components/layout/header/barranav";


export default function Form() {
  return (
    <>
    <Head>
        <title>Formularios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="/favicon.ico" />
        <Barranav />
      </Head>
    
    <main>
      
    <h1>Formularios</h1>
    <p>Los formularios se utilizan para recopilar datos del usuario.</p>
    <h2>Etiqueta form</h2>
    <p>La etiqueta form se utiliza para crear un formulario en una página web.</p>
    <h2>Etiqueta input</h2>
    <p>La etiqueta input se utiliza para crear un campo de entrada en un formulario.</p>
    <h2>Atributo type</h2>
    <p>El atributo type especifica el tipo de campo de entrada.</p>
    <h2>Atributo value</h2>
    <p>El atributo value especifica el valor del campo de entrada.</p>
    <h2>Atributo required</h2>
    <p>El atributo required especifica que el campo de entrada es obligatorio.</p>
    <h2>Etiqueta select</h2>
    <p>La etiqueta select se utiliza para crear un menú desplegable en un formulario.</p>
    <h2>Etiqueta option</h2>
    <p>La etiqueta option se utiliza para definir una opción en un menú desplegable.</p>
    <h2>Atributo send</h2>
    <p>El atributo send especifica que el formulario se ha enviado.</p>
    <h2>Etiqueta label</h2>
    <p>La etiqueta label se utiliza para definir una etiqueta para un campo de entrada en un formulario.</p>
    <h2>Comentarios</h2>
    <p>Los comentarios se pueden añadir a un formulario con la etiqueta textarea.</p>
    <h2>Atributo rows</h2>
    <p>El atributo rows especifica el número de filas en un campo de comentarios.</p>
    <h2>Atributo cols</h2>
    <p>El atributo cols especifica el número de columnas en un campo de comentarios.</p>
    <h2>Ejemplo</h2>
    

    <form action = "/submit-your-form-handler" method = "POST">
      <label htmlFor="name">Nombre:</label><br/>
      <input type="text" id="name" name="name" required/><br/>
      <label htmlFor="email">Email:</label><br/>
      <input type="email" id="email" name="email" required/><br/>
      <label htmlFor="birthday">Fecha de nacimiento:</label><br/>
      <input type="date" id="birthday" name="birthday" required/><br/>

      <label htmlFor="musicGenre">Género musical:</label><br/>
      <select id="musicGenre" name="musicGenre" required>
        <option value="Jazz">Jazz</option>
        <option value="Blues">Blues</option>
        <option value="Rock">Rock</option>
        <option value="Soul">Soul</option>
        <option value="R&B">R&B</option>
      </select><br/>

      <label htmlFor="comments">Comentarios:</label><br/>
      <textarea id="comments" name="comments" rows={4} cols={50}></textarea><br/>

      <label htmlFor="send">Enviar:</label><br/>
      <input type="submit" id="send" name="send" value="Enviar"/> <br/>

    </form>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
      
    
      <button><a href="/HTML">Anterior</a></button>

    </main>
    </>
  );
}

