import Head from "next/head";
import Image from "next/image";
import Barranav from "../../../components/layout/header/barranav";

export default function Home() {
  return (
    <>
    <Head>
        <title>Párrafos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="/favicon.ico" />
        <Barranav />
      </Head>
    
    <main>
      <h1>Etiqueta p</h1>
      <p>La etiqueta p se utiliza para definir un párrafo.</p>
      <p>Un párrafo siempre comienza en una nueva línea y se añade un espacio en blanco arriba y abajo del párrafo.</p>
      <p>Los márgenes superior e inferior, así como el espaciado entre párrafos, se pueden modificar con CSS (con las propiedades margin y padding).</p>
      <p>Los navegadores web automáticamente añaden un margen antes y después de un párrafo.</p>
      <p>Los márgenes se pueden modificar con CSS (con la propiedad margin).</p>
      <h2>Ejemplo:</h2>
      <p>Este es un ejemplo de un párrafo en HTML.</p>
      <button><a href="/HTML">Anterior</a></button>

    </main>
    </>
  );
}

