import Head from "next/head";
import Image from "next/image";
import Barranav from "../components/layout/header/barranav";
import Contador from "@/components/pages/home/footer/contador";
export default function Home() {
  return (
    <>
    <Head>
        <title>Documentación</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="/favicon.ico" />
        
      </Head>
    
    <header>
    <Barranav />
    </header>
    <main>
    </main>
    
    <footer>
      <Contador />
    </footer>

    </>
  );
}

