import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Barranav from "../../../components/layout/header/barranav";



export default function Comp() {
  return (
    <>
      <Head>
        <title>Componentes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
        <Barranav />
      </Head>
      
      <main>


      
      <h1>Componentes</h1>
      <p>Los componentes son bloques de construcción de React. Un componente es una parte de la interfaz de usuario que se puede reutilizar en una aplicación.</p>
      <h2>Componentes de función</h2>
      <p>Un componente de función es una función de JavaScript que devuelve un elemento de React.</p>
      <h2>Componentes de clase</h2>
      <p>Un componente de clase es una clase de JavaScript que extiende React.Component.</p>
      <h2>Props</h2>
      <p>Las props son argumentos que se pasan a un componente de React.</p>
      <h2>Estado</h2>
      <p>El estado es un objeto que contiene datos y determina cómo se ve un componente.</p>
      <h2>Ciclo de vida</h2>
      <p>El ciclo de vida de un componente de React consta de tres fases: montaje, actualización y desmontaje.</p>
      <h2>Renderizado condicional</h2>
      <p>El renderizado condicional se utiliza para mostrar diferentes elementos en función de una condición.</p>
      <h2>Eventos</h2>
      <p>Los eventos se utilizan para manejar las interacciones del usuario con un componente.</p>
      <h2>Estilos</h2>
      <p>Los estilos se utilizan para dar estilo a un componente.</p>
      <h2>Componentes de terceros</h2>
      <p>Los componentes de terceros son componentes creados por otros desarrolladores.</p>
      <h2>Contexto</h2>
      <p>El contexto se utiliza para pasar datos a través del árbol de componentes sin tener que pasar props manualmente en cada nivel.</p>
      <h2>Refs</h2>
      <p>Las refs se utilizan para acceder al DOM o a un componente hijo de un componente de React.</p>
      <h2>Fragmentos</h2>
      <p>Los fragmentos se utilizan para agrupar elementos hijos sin agregar nodos adicionales al DOM.</p>
      <h2>Portales</h2>
      <p>Los portales se utilizan para renderizar un componente en un nodo DOM que está fuera del árbol de componentes principal.</p>
      <h2>Errores</h2>
      <p>Los errores se utilizan para manejar errores en un componente de React.</p>
      <h2>Pruebas</h2>
      <p>Las pruebas se utilizan para probar un componente de React.</p>
      <h2>Optimización</h2>
      <p>La optimización se utiliza para mejorar el rendimiento de un componente de React.</p>
      <h2>Conclusión</h2>
      <p>Los componentes son bloques de construcción de React que se pueden reutilizar en una aplicación.</p>
      <h2>Referencias</h2>
      <Link href={"https://es.react.dev/learn"}>
        Get Started
      </Link>

      <br/>
      <br/>



      <button><a href="/React">Anterior</a></button>

      </main>

    </>
  );
}

