import Head from "next/head";
import Image from "next/image";
import Barranav from "../../../components/layout/header/barranav";

export default function Table() {
  return (
    <>
    <Head>
        <title>Tablas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="/favicon.ico" />
        <Barranav />
      </Head>
    
    <main>
      <h1>Tablas</h1>
      <p>Las tablas se utilizan para mostrar datos en filas y columnas.</p>
      <h2>Etiqueta table</h2>
      <p>La etiqueta table se utiliza para crear una tabla.</p>
      <p>Una tabla comienza con la etiqueta table y cada fila de la tabla comienza con la etiqueta tr.</p>
      <p>Las celdas de la tabla se definen con la etiqueta td.</p>
      <h2>Etiqueta tr</h2>
      <p>La etiqueta tr se utiliza para definir una fila en una tabla.</p>
      <p>Una fila de la tabla comienza con la etiqueta tr y cada celda de la fila comienza con la etiqueta td.</p>
      <h2>Etiqueta td</h2>
      <p>La etiqueta td se utiliza para definir una celda en una tabla.</p>
      <p>Una celda de la tabla se define con la etiqueta td y puede contener texto, imágenes, enlaces, etc.</p>
      <h2>Etiqueta th</h2>
      <p>La etiqueta th se utiliza para definir una celda de encabezado en una tabla.</p>
      <p>Una celda de encabezado se define con la etiqueta th y se utiliza para encabezados de columna o fila.</p>
      <h2>Ejemplo:</h2>
      <table border = "3">
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Edad</th>
          <th>País</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>Juan</td>
          <td>25</td>
          <td>Argentina</td>
        </tr>
        <tr>
          <td>María</td>
          <td>30</td>
          <td>México</td>
        </tr>
        <tr>
          <td>Carlos</td>
          <td>35</td>
          <td>Chile</td>
        </tr>
        </tbody>
      </table>

      

    
      <button><a href="/HTML">Anterior</a></button>

    </main>
    </>
  );
}

